import NexenPlayer from './components/NexenPlayer';
import {
  Source,
  NexenSource,
  NexenConfig,
  // OptimizationConfig,
  ControlHideMode,
  LayoutMode,
  EdgeInsets,
  PlaybackSpeed,
  PlayList,
  PlayListItem,
  TextTrack,
  SelectedTextTrack,
  SelectedAudioTrack,
  NexenPlayerProps,
  NexenPlayerRef,
} from './components/NexenPlayer';
export default NexenPlayer;
export {
  Source,
  NexenSource,
  NexenConfig,
  // OptimizationConfig,
  ControlHideMode,
  LayoutMode,
  EdgeInsets,
  PlaybackSpeed,
  PlayList,
  PlayListItem,
  TextTrack,
  SelectedTextTrack,
  SelectedAudioTrack,
  NexenPlayerProps,
  NexenPlayerRef,
};
